name: demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: stoe-demo/read-json-action-demo@main
        id: read-json
        with:
          json_file_path: 'package.json'